# Motor Controller Configuration
device_id: "motor_controller_001"
device_name: "Motor Controller"
device_type: "actuator"
data_configs:
  - name: "rpm"
    data_type: "integer"
    min_value: 0
    max_value: 3000
    frequency: 10.0  # 10 Hz
    change_step: 50  # Max 50 RPM change per second
    unit: "RPM"
    initial_value: 0
    noise_level: 0.01  # 1% noise
    drift_rate: 0.0
    custom_params:
      target_rpm: 1500
      
  - name: "temperature"
    data_type: "float"
    min_value: 20.0
    max_value: 80.0
    frequency: 1.0  # 1 Hz
    change_step: 2.0  # Max 2°C change per second
    unit: "°C"
    initial_value: 25.0
    noise_level: 0.02  # 2% noise
    drift_rate: 0.1  # Gradual heating
    custom_params:
      precision: 1
      
  - name: "status"
    data_type: "string"
    min_value: 0.0
    max_value: 1.0
    frequency: 0.2  # 0.2 Hz (every 5 seconds)
    change_step: 0.05  # 5% chance to change per second
    unit: ""
    initial_value: null
    noise_level: 0.0
    drift_rate: 0.0
    custom_params:
      string_length: 10
      string_chars: "abcdefghijklmnopqrstuvwxyz"
      possible_states: ["idle", "running", "error", "maintenance"]
      
  - name: "power_consumption"
    data_type: "float"
    min_value: 0.0
    max_value: 1000.0
    frequency: 5.0  # 5 Hz
    change_step: 10.0  # Max 10W change per second
    unit: "W"
    initial_value: 0.0
    noise_level: 0.03  # 3% noise
    drift_rate: 0.0
    custom_params:
      precision: 1

communication:
  protocol: "tcp"
  port: 8082
  buffer_size: 2048

metadata:
  location: "Production Line 1"
  manufacturer: "MotorTech"
  model: "MotorCtrl-3000"
