# Pressure Sensor Configuration
device_id: "pressure_sensor_001"
device_name: "Pressure Sensor"
device_type: "sensor"
data_configs:
  - name: "pressure"
    data_type: "float"
    min_value: 0.0
    max_value: 10.0
    frequency: 2.0  # 2 Hz
    change_step: 0.1  # Max 0.1 bar change per second
    unit: "bar"
    initial_value: 1.0
    noise_level: 0.005  # 0.5% noise
    drift_rate: 0.0001  # Very slow drift
    custom_params:
      precision: 3  # 3 decimal places
      
  - name: "status"
    data_type: "boolean"
    min_value: 0
    max_value: 1
    frequency: 0.1  # 0.1 Hz (every 10 seconds)
    change_step: 0.01  # 1% chance to change per second
    unit: ""
    initial_value: true
    noise_level: 0.0
    drift_rate: 0.0
    custom_params: {}

communication:
  protocol: "tcp"
  port: 8081
  buffer_size: 1024

metadata:
  location: "Tank B"
  manufacturer: "PressureTech"
  model: "PressSense-5000"
