# Temperature Sensor Configuration
device_id: "temp_sensor_001"
device_name: "Temperature Sensor"
device_type: "sensor"
data_configs:
  - name: "temperature"
    data_type: "float"
    min_value: -40.0
    max_value: 85.0
    frequency: 1.0  # 1 Hz
    change_step: 0.5  # Max 0.5°C change per second
    unit: "°C"
    initial_value: 20.0
    noise_level: 0.02  # 2% noise
    drift_rate: 0.001  # 0.001°C per second drift
    custom_params:
      precision: 1  # 1 decimal place
      
  - name: "humidity"
    data_type: "float"
    min_value: 0.0
    max_value: 100.0
    frequency: 0.5  # 0.5 Hz
    change_step: 1.0  # Max 1% change per second
    unit: "%"
    initial_value: 50.0
    noise_level: 0.01  # 1% noise
    drift_rate: 0.0  # No drift
    custom_params:
      precision: 1

communication:
  protocol: "tcp"
  port: 8080
  buffer_size: 1024

metadata:
  location: "Room A"
  manufacturer: "SensorCorp"
  model: "TempSense-2000"
