# Default configuration for Device Emulator and Qt Client

# Device Emulator Configuration
device_emulator:
  # Default device settings
  default_device:
    type: "sensor"
    sampling_rate: 1000  # Hz
    data_format: "json"
    
  # Communication settings
  communication:
    protocol: "tcp"
    host: "localhost"
    port: 8080
    buffer_size: 1024
    
  # Simulation settings
  simulation:
    enable_noise: true
    noise_level: 0.1
    enable_drift: true
    drift_rate: 0.01

# Qt Client Configuration
qt_client:
  # UI settings
  ui:
    theme: "light"  # light, dark
    window_size: [1200, 800]
    auto_resize: true
    
  # Data visualization settings
  visualization:
    update_interval: 100  # ms
    max_data_points: 1000
    chart_type: "line"  # line, scatter, bar
    
  # Data handling
  data:
    buffer_size: 10000
    auto_save: true
    save_interval: 300  # seconds

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/application.log"
  max_size: 10485760  # 10MB
  backup_count: 5
